name: ⚡ 本地编译

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ github.event.inputs.device }}
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout
      continue-on-error: true
      uses: actions/checkout@main

    - name: Setup variables
      run: |
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'

    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo

    - name: Compile OpenWrt
      id: compile
      continue-on-error: true
      run: |
        export ${{ github.event.inputs.build_options }} LAN=${{ github.event.inputs.lan_addr }} WIFI_NAME=${{ github.event.inputs.wifi_name }}
        [ -n ${{ github.event.inputs.root_password }} ] && export ROOT_PASSWORD="${{ github.event.inputs.root_password }}"
        bash <(curl -sS http://127.0.0.1:8080/build.sh) ${{ github.event.inputs.device }}
        cd openwrt
        tags=$(git branch --show-current)
        echo "latest_release=$tags"

    - name: Extensive logs after a failed compilation
      if: steps.compile.outcome == 'failure'
      run: |
        cd openwrt
        make V=s
        
    - name: Prepare Firmware Files
      run: |
        mkdir -p rom
        case "${{ github.event.inputs.device }}" in
          cetron-ct3003)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          cmcc-a10)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          h3c-magic-nx30-pro)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          imou-lc-hx3001)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          nokia-ea0326gmp)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          qihoo-360t7)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          newland-nl-wr8103)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          umi-uax3000e)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          clx-s20p)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          netcore-n60-pro)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          netcore-n60-pro-512rom)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          xiaomi-redmi-router-ax6000)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
            xiaomi-redmi-router-ax6000-512rom)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
          jdcloud-re-cp-03)
              cp -a openwrt/bin/targets/mediatek/*/*-sysupgrade.bin rom/
              ;;
        esac

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.device }}-openwrt-24.10
        path: builder/rom/*

    - name: Create release
      continue-on-error: true
      uses: ncipollo/release-action@v1
      with:
        name: openwrt-24.10
        allowUpdates: true
        tag: openwrt-24.10
        commit: main
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: builder/rom/*
